# syntax=docker/dockerfile:experimental
FROM alpine:3.8
RUN --mount=type=bind,source=packages/racket-alpine,target=/repo \
    apk add --allow-untrusted /repo/`apk --print-arch`/racket-[0-9]*.apk
CMD racket
